/**
 * Provenance Tracking Types
 *
 * Implements CAMEL-inspired data provenance tracking for prompt injection defense.

/**
 * Provenance tracking mode enum
 */
export enum ProvenanceMode {
	/** No provenance tracking - zero overhead */
	NONE = 'none',
	/** Proxy-based tracking - runtime tracking */
	PROXY = 'proxy',
	/** AST instrumentation - compile-time tracking */
	AST = 'ast',
}

/**
 * Data source types
 */
export enum ProvenanceSource {
	/** Direct from user input (trusted) */
	USER = 'user',
	/** From LLM generation */
	LLM = 'llm',
	/** From tool execution */
	TOOL = 'tool',
	/** Generated by runtime/system */
	SYSTEM = 'system',
}

/**
 * Tool source metadata
 */
export interface ToolSource {
	type: ProvenanceSource.TOOL;
	toolName: string;
	apiGroup: string;
	timestamp: number;
}

/**
 * LLM source metadata
 */
export interface LLMSource {
	type: ProvenanceSource.LLM;
	operation: 'call' | 'extract' | 'classify';
	timestamp: number;
}

/**
 * User source metadata
 */
export interface UserSource {
	type: ProvenanceSource.USER;
	timestamp: number;
}

/**
 * System source metadata
 */
export interface SystemSource {
	type: ProvenanceSource.SYSTEM;
	operation: string;
	timestamp: number;
}

/**
 * Source metadata union
 */
export type SourceMetadata = ToolSource | LLMSource | UserSource | SystemSource;

/**
 * Reader permissions - who can access this data
 */
export type ReaderPermissions = { type: 'public' } | { type: 'restricted'; readers: string[] };

/**
 * Complete provenance metadata
 */
export interface ProvenanceMetadata {
	/** Where this data came from */
	source: SourceMetadata;

	/** Who can read this data */
	readers: ReaderPermissions;

	/** Chain of dependencies (for tracking data flow) */
	dependencies?: string[];

	/** Unique identifier for this provenance record */
	id: string;

	/** Additional context */
	context?: Record<string, unknown>;
}

/**
 * Serialized provenance state for pause/resume
 */
export interface ProvenanceState {
	registry: Array<[string, ProvenanceMetadata]>;
}

/**
 * Enhanced provenance snapshot including primitive taints
 * Used for cross-execution token persistence
 */
export interface ProvenanceSnapshot {
	/** Object provenance registry */
	registry: Array<[string, ProvenanceMetadata]>;
	/** Primitive taint mappings */
	primitives: Array<[string, ProvenanceMetadata]>;
}

/**
 * Policy action types
 * - log: Allow operation but log security event for audit
 * - approve: Pause and request human approval
 * - block: Deny operation immediately
 */
export type PolicyAction = 'log' | 'approve' | 'block';

/**
 * Security policy result
 */
export interface PolicyResult {
	/** @deprecated Use action instead */
	allowed?: boolean;

	/**
	 * Action to take:
	 * - log: Allow but audit (permissive monitoring)
	 * - approve: Request human approval (interactive gating)
	 * - block: Deny immediately (maximum security)
	 */
	action: PolicyAction;

	/** Human-readable reason for the action */
	reason?: string;

	/** Policy name that produced this result */
	policy?: string;

	/** Additional context for approval UI (when action='approve') or audit log */
	context?: Record<string, unknown>;
}

/**
 * Security policy interface
 */
export interface SecurityPolicy {
	name: string;
	description?: string;
	check: (
		toolName: string,
		args: Record<string, unknown>,
		getProvenance: (value: unknown) => ProvenanceMetadata | null
	) => PolicyResult | Promise<PolicyResult>;
}

/**
 * Provenance security policy violation error
 */
export class ProvenanceSecurityError extends Error {
	constructor(
		message: string,
		public policy: string,
		public toolName: string,
		public details?: Record<string, unknown>
	) {
		super(message);
		this.name = 'ProvenanceSecurityError';
	}
}
